const mediasData = {
  nodes : [
    /* SITES */
    {id:'4chan', name:"4chan", objToString:"fourChan", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '00-fourChan.png', size:'big',
    related:{ memes:[0, 1, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    {id:'reddit', name:"Reddit", objToString:"reddit", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '01-reddit.png', size:'big',
    related:{ memes:[0, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    {id:'discord', name:"Discord", objToString:"discord", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '02-discord.png', size:'big',
    related:{ memes:[],
      events:[2,4],
      peoples:[0, 1, 2],
    }},
    {id:'jvc1825', name:"Forum 18-25 Jeuvideo.com", objToString:"jvc1825", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '03-jvc1825.png', size:'big',
    related:{ memes:[0, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    {id:'r-the-donald', name:"/r/The_Donald", objToString:"rTheDonald", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '04-rTheDonald.png', size:'big',
    related:{ memes:[0, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    {id:'sanders-stash', name:"Bernie Sanders' Dank Meme Stash", objToString:"sandersStash", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '05-sandersStash.png', size:'big',
    related:{ memes:[0, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    {id:'twitter', name:"Twitter", objToString:"twitter", mainNode: true,  type:'site', folder:"./assets/pics/3-medias/",img: '06-twitter.png', size:'big',
    related:{ memes:[0, 2],
      events:[0, 1, 2],
      peoples:[0, 1, 2],
    }},
    /* 4CHAN */
    {id:'4chan-node-1', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-1', name:"Marine Le Pen fait un selfie controversé avec un militant radical estonien «suprémaciste»", author:"Le Figaro", link:'http://www.lefigaro.fr/politique/le-scan/couacs/marine-le-pen-fait-un-selfie-controverse-avec-un-militant-radical-estonien-supremaciste-20190514'},
    {id:'4chan-node-2', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-2', name:"Lâche-toi, 4chan t’hébergera", author:"Télérama", link:'https://www.telerama.fr/techno/lache-toi-4chan-t-hebergera,55584.php'},
    {id:'4chan-node-3', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-3', name:"Le camp Macron déconstruit point par point la rumeur sur le compte offshore", author:"BFMTV", link:'https://www.bfmtv.com/politique/le-camp-macron-deconstruit-point-par-point-l-insinuation-de-le-pen-sur-le-compte-aux-bahamas-1156799.html'},
    {id:'4chan-node-4', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-4', name:"How pro-Trump trolls spread fake news from 4chan to influence French elections", author:"Mashable", link:'https://mashable.com/2017/05/04/pro-trump-fake-news-emmanuel-macron-marine-le-pen/'},
    {id:'4chan-node-5', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-5', name:"Les «Macron Leaks», une boule puante venue de l'extrême droite américaine", author:"Mediapart", link:'https://www.mediapart.fr/journal/france/060517/les-macron-leaks-une-boule-puante-venue-de-lextreme-droite-americaine'},
    {id:'4chan-node-6', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-6', name:"Présidentielle 2017 : comment des internautes américains font le jeu de Le Pen", author:"RTL", link:'https://www.rtl.fr/actu/politique/presidentielle-2017-comment-des-internautes-americains-font-le-jeu-de-le-pen-7788314666'},
    {id:'4chan-node-7', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-7', name:"Où en est la plainte de Macron contre l'intox du compte aux Bahamas durant la campagne ?", author:"Libération - Check News", link:'https://www.liberation.fr/checknews/2018/06/05/ou-en-est-la-plainte-de-macron-contre-l-intox-du-compte-aux-bahamas-durant-la-campagne_1656580'},
    {id:'4chan-node-8', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-8', name:"A Complete Timeline Of How Trump Supporters Tried — And Failed — To Hijack The French Election", author:"BuzzFeed News", link:'https://www.buzzfeednews.com/article/ryanhatesthis/how-the-american-far-right-tired-and-failed-to-hijack-the'},
    {id:'4chan-node-9', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-9', name:"Des conseillers avaient suggéré à Marine Le Pen de balancer en plein débat la fake news sur le compte offshore d'Emmanuel Macron aux Bahamas", author:"Le Lab Europe 1", link:'http://lelab.europe1.fr/des-conseillers-avait-suggere-a-marine-le-pen-de-balancer-en-plein-debat-la-fake-news-sur-le-compte-offshore-demmanuel-macron-aux-bahamas-3545894'},
    {id:'4chan-node-10', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-10', name:"Sur 4Chan, les anti-Macron diffusent mèmes accusateurs et fausses rumeurs", author:"L'Express", link:'https://lexpansion.lexpress.fr/high-tech/sur-4chan-les-anti-macron-diffusent-memes-accusateurs-et-fausses-rumeurs_1901827.html'},
    {id:'4chan-node-11', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-11', name:"D'où vient l'intox de Marine Le Pen sur Macron et les Bahamas?", author:"Le Journal De Dimanche", link:'https://www.lejdd.fr/Politique/compte-aux-bahamas-dou-vient-la-rumeur-relayee-par-le-pen-face-a-macron-3319625'},
    {id:'4chan-node-12', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-12', name:"Compte offshore: Macron accuse Marine Le Pen de propager des \"fake news\"", author:"Le Point", link:'https://www.lepoint.fr/politique/compte-offshore-macron-accuse-marine-le-pen-de-propager-des-fake-news-04-05-2017-2124734_20.php'},
    {id:'4chan-node-13', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-13', name:"Les trolls de 4chan sont persuadés d'avoir fait élire Donald Trump", author:"Slate", link:'http://www.slate.fr/story/128864/4chan-victoire-donald-trump'},
    {id:'4chan-node-14', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-14', name:"Sur Internet, l’extrême droite pro-Trump pleure la victoire d’Emmanuel Macron", author:"Le Monde - Pixels", link:'https://www.lemonde.fr/pixels/article/2017/05/08/sur-internet-l-extreme-droite-pro-trump-pleure-la-victoire-d-emmanuel-macron_5124226_4408996.html'},
    {id:'4chan-node-15', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-15', name:"Des communautés de 4chan s'organisent pour lancer des fake news sur Emmanuel Macron", author:"France 24", link:'https://www.france24.com/fr/20170424-communautes-4chan-sorganisent-lancer-fake-news-emmanuel-macron'},
    {id:'4chan-node-16', parent:"4chan", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'4chan-16', name:"Trump's Troll Army", author:"Wikipedia", link:'https://fr.wikipedia.org/wiki/Trump%27s_Troll_Army'},
    {id:'4chan-node-17', parent:"4chan", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'4chan-17', name:"4chan", author:"Wikipedia", link:'https://fr.wikipedia.org/wiki/4chan'},
    {id:'4chan-node-18', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-18', name:"\"The Great Meme War\" : comment les trolls de 4chan ont porté Trump au pouvoir", author:"Les Inrockuptibles", link:'https://www.lesinrocks.com/2017/03/28/medias/medias/the-great-meme-war-comment-les-trolls-de-4chan-ont-port%C3%A9-trump-au-pouvoir/'},
    {id:'4chan-node-19', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-19', name:"Reddit, 4Chan : la victoire de Trump, c’est la victoire des trolls", author:"L'Obs", link:'https://www.nouvelobs.com/rue89/rue89-sur-les-reseaux/20161109.RUE4199/reddit-4chan-la-victoire-de-trump-c-est-la-victoire-des-trolls.html'},
    {id:'4chan-node-20', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-20', name:"Trump-endorsed One America News Network among right-wing amplifiers of Jacob Wohl's attempted smear of Pete Buttigieg", author:"Media Matters", link:'https://www.mediamatters.org/networks-and-outlets/4chan'},
    {id:'4chan-node-21', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-21', name:"Mapping the meme: How a viral image went from 4chan and QAnon supporters to Trump’s Twitter", author:"Media Matters", link:'https://www.mediamatters.org/research/2018/11/28/Mapping-the-meme-How-a-viral-image-went-from-4chan-and-QAnon-supporters-to-Trumps-Twitter/222176'},
    {id:'4chan-node-22', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-22', name:"Comment 4chan a retrouvé le livestream de Shia LaBeouf au milieu de nulle part - et l'a ruiné", author:"Vice", link:'https://www.vice.com/fr/article/9amqjd/comment-4chan-a-retrouve-le-livestream-de-shia-labeouf-au-milieu-de-nulle-part-et-la-ruine'},
    {id:'4chan-node-23', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-23', name:"Qui est Qanon, ce groupe pro-Trump adepte de théories du complot?", author:"20 Minutes", link:'https://www.20minutes.fr/monde/2316919-20180803-qanon-groupe-pro-trump-adepte-theories-complot'},
    {id:'4chan-node-24', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-24', name:"What is 4chan, did it predict the London terror attack and how was the website involved in the Donald Trump dossier scandal?", author:"The Sun", link:'https://www.thesun.co.uk/news/2599048/4chan-donald-trump/'},
    {id:'4chan-node-25', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-25', name:"Rep. Devin Nunes repeated a 4chan meme on national television", author:"The Verge", link:'https://www.theverge.com/2019/2/8/18217528/rep-devin-nunes-4chan-meme-fox-news-tucker-carlson'},
    {id:'4chan-node-26', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-26', name:"Andrew Yang Wants The Support Of The Pro-Trump Internet. Now It Is Threatening To Devour Him.", author:"BuzzFeed News", link:'https://www.buzzfeednews.com/article/ryanhatesthis/4chan-vs-the-yang-gang'},
    {id:'4chan-node-27', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-27', name:"Teenager Arrested In Charlottesville After 4Chan Threat On School", author:"The Huffington Post", link:'https://www.huffpost.com/entry/juvenile-arrested-in-charlottesville-after-4chan-threat-on-school_n_5c9508a6e4b0a6329e15f2bd'},
    {id:'4chan-node-28', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-28', name:"Attentat de Christchurch : des FAI ont bloqué 4chan et 8chan sans décision de la justice", author:"Numerama", link:'https://www.numerama.com/politique/473554-attentat-de-christchurch-des-fai-ont-bloque-4chan-et-8chan-sans-decision-de-la-justice.html'},
    {id:'4chan-node-29', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-29', name:"Ignore The Poway Synagogue Shooter’s Manifesto: Pay Attention To 8chan’s /pol/ Board", author:"Bellingcat", link:'https://www.bellingcat.com/news/americas/2019/04/28/ignore-the-poway-synagogue-shooters-manifesto-pay-attention-to-8chans-pol-board/'},
    {id:'4chan-node-30', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-30', name:"The Christchurch shooting suspect comes from an extreme online culture", author:"The Washington Post", link:'https://www.washingtonpost.com/politics/2019/03/15/christchurch-shooting-suspect-comes-an-extreme-online-culture/'},
    {id:'4chan-node-31', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-31', name:"Attentat de Christchurch : dans la tête du terroriste, tout a commencé en France", author:"Le Parisien", link:'http://www.leparisien.fr/faits-divers/attentat-de-christchurch-dans-la-tete-du-terroriste-tout-a-commence-en-france-15-03-2019-8032380.php'},
    {id:'4chan-node-32', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-32', name:"People On 4chan Appear To Be Having A Complete Meltdown Over The Election Right Now", author:"BuzzFeed News", link:'https://www.buzzfeednews.com/article/ryanhatesthis/people-on-4chan-appear-to-be-having-a-complete-meltdown-over'},
    {id:'4chan-node-33', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-33', name:"World War Meme", author:"Politico", link:'https://www.politico.com/magazine/story/2017/03/memes-4chan-trump-supporters-trolls-internet-214856'},
    {id:'4chan-node-34', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-34', name:"Le forum 4chan s'invite dans l'élection présidentielle française", author:"Le Figaro", link:'http://www.lefigaro.fr/secteur/high-tech/2017/05/04/32001-20170504ARTFIG00215-le-forum-4chan-s-invite-dans-l-election-presidentielle-francaise.php'},
    {id:'4chan-node-35', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-35', name:"Les autorités américaines enquêtent sur le forum 4chan après la fusillade en Oregon", author:"Le Figaro", link:'http://www.lefigaro.fr/secteur/high-tech/2015/10/02/32001-20151002ARTFIG00100-les-autorites-americaines-enquetent-sur-le-forum-4chan-apres-la-fusillade-en-oregon.php'},
    {id:'4chan-node-36', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-36', name:"Sur le forum 4chan, un message ciblait Westminster la veille de l'attentat de Londres", author:"Le Figaro", link:'http://www.lefigaro.fr/secteur/high-tech/2017/03/23/32001-20170323ARTFIG00274-sur-le-forum-4chan-un-message-ciblait-westminster-la-veille-de-l-attentat-de-londres.php'},
    {id:'4chan-node-37', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-37', name:"Russia investigation to probe “foul corners” of 4Chan and Reddit", author:"Vice News", link:'https://news.vice.com/en_ca/article/mb95w3/russia-investigation-to-probe-foul-corners-of-4chan-and-reddit'},
    {id:'4chan-node-38', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-38', name:"8chan is at the center of the Christchurch mosque shootings—and its roots are in Gamergate (updated)", author:"The Daily Dot", link:'https://www.dailydot.com/layer8/8chan-christchurch-mosque-shooter-gamergate/'},
    {id:'4chan-node-39', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-39', name:"Trolling Scholars Debunk the Idea That the Alt-Right’s Shitposters Have Magic Powers", author:"Motherboard - Vice", link:'https://www.vice.com/en_us/article/z4k549/trolling-scholars-debunk-the-idea-that-the-alt-rights-trolls-have-magic-powers'},
    {id:'4chan-node-40', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-40', name:"No, You Can't Vote Online: Trolls From 4chan Are Spreading Misinformation to Suppress Voters", author:"Complex", link:'https://www.complex.com/life/2016/11/trolls-4chan-spreading-misinformation-election'},
    {id:'4chan-node-41', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-41', name:"How a 4chan wannabe galvanised Spain's far-right election upstarts", author:"WIRED", link:'https://www.wired.co.uk/article/spain-election-far-right-vox'},
    {id:'4chan-node-42', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-42', name:"Why 4chan is 'struggling to survive'", author:"BBC News", link:'https://www.bbc.com/news/technology-37563647'},
    {id:'4chan-node-43', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-43', name:"Quand BuzzFeed (et 4Chan ?) devient une source fiable pour L’Obs", author:"Mediapart", link:'https://blogs.mediapart.fr/danyves/blog/120117/quand-buzzfeed-et-4chan-devient-une-source-fiable-pour-l-obs-bravo-boris-mane'},
    {id:'4chan-node-44', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-44', name:"«MacronLeaks» : tentative de déstabilisation à la dernière minute", author:"Libération", link:'https://www.liberation.fr/politiques/2017/05/06/macronleaks-tentative-de-destabilisation-a-la-derniere-minute_1567718'},
    {id:'4chan-node-45', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-45', name:"Americans on Twitter, Reddit and 4Chan: ‘Apparently You Have to Register to Vote?’", author:"The Daily Beast", link:'https://www.thedailybeast.com/americans-on-twitter-reddit-and-4chan-apparently-you-have-to-register-to-vote'},
    {id:'4chan-node-46', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-46', name:"How the alt-right uses internet trolling to confuse you into dismissing its ideology", author:"Vox", link:'https://www.vox.com/2016/11/23/13659634/alt-right-trolling'},
    {id:'4chan-node-47', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-47', name:"Trump's Troll Army Is Having a Hard Time Voting", author:"Gizmodo", link:'https://gizmodo.com/trumps-troll-army-is-having-a-hard-time-voting-1788712609'},
    {id:'4chan-node-48', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-48', name:"The rise of 4chan politics", author:"TechCrunch", link:'https://techcrunch.com/2016/12/21/the-rise-of-4chan-politics/'},
    {id:'4chan-node-49', parent:"4chan", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'4chan-49', name:"4chan: The Skeleton Key To The Rise Of Trump", author:"The Huffington Post", link:"https://www.huffpost.com/entry/4chan-the-skeleton-key-to-the-rise-of-trump_b_58ab6156e4b0a855d1d8dfe4"},
    /* DISCORD */
    {id:'discord-node-1', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-1', name:"Discord insoumis", author:"Wikipedia", link:'https://fr.wikipedia.org/wiki/Discord_insoumis'},
    {id:'discord-node-2', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-2', name:"Un an dans l'intimité de la Taverne des Patriotes, repaire de militants nationalistes", author:"Slate", link:'http://www.slate.fr/story/165929/taverne-des-patriotes-election-presidentielle-2017-front-national-militants-extreme-droite-discord'},
    {id:'discord-node-3', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-3', name:"Macron face à Le Pen : on a suivi les débats des Insoumis sur Discord", author:"Marianne", link:'https://www.marianne.net/politique/macron-face-le-pen-suivi-les-debats-des-insoumis-sur-discord'},
    {id:'discord-node-4', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-4', name:"Les pro-Mélenchon débattent de leurs options sur le Discord des Insoumis", author:"L'Express", link:'https://www.lexpress.fr/actualite/politique/lfi/les-pro-melenchon-debattent-de-leurs-options-sur-le-discord-des-insoumis_1902109.html'},
    {id:'discord-node-5', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-5', name:"A YouTuber Standing As A UKIP Candidate Invited Supporters To A Gaming Community That Has Chatrooms Filled With White Supremacist And Anti-Semitic Content", author:"BuzzFeed News", link:'https://www.buzzfeed.com/markdistefano/sargon-akkad-discord-ukip-mep-campaign'},
    {id:'discord-node-6', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-6', name:"White nationalists and the alt-right are disillusioned with Trump — and some are joining the Yang Gang", author:"Insider", link:'https://www.insider.com/white-supremacists-are-disillusioned-by-trump-and-joining-the-yang-gang-2019-3'},
    {id:'discord-node-7', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-7', name:"Andrew Yang Is the Tech-Loving 2020 Candidate Promising Free Money for All", author:"Vice", link:'https://www.vice.com/en_us/article/qvynnp/meet-the-tech-loving-presidential-candidate-promising-free-money-for-all'},
    {id:'discord-node-8', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-8', name:"ANDREW YANG IS THE CANDIDATE FOR THE END OF THE WORLD", author:"The Verge", link:'https://www.theverge.com/2019/4/17/18408685/andrew-yang-2020-president-democrat-candidate-policies-universal-basic-income-reddit-twitter'},
    {id:'discord-node-9', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-9', name:"Andrew Yang is running for president. Haven’t heard of him? You will soon.", author:"The Washington Post", link:'https://www.washingtonpost.com/politics/2019/03/14/andrew-yang-is-running-president-havent-heard-him-you-will-soon/'},
    {id:'discord-node-10', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-10', name:"Comment fonctionne «Discord insoumis», l'outil numérique pro-Mélenchon?", author:"20 Minutes", link:'https://www.20minutes.fr/high-tech/2051815-20170418-comment-fonctionne-discord-insoumis-outil-numerique-pro-melenchon'},
    {id:'discord-node-11', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-11', name:"C’est quoi, Discord ? (En tout cas, pas le réseau social de la France Insoumise)", author:"Numérama", link:'https://www.numerama.com/tech/292065-cest-quoi-discord-en-tout-cas-pas-le-reseau-social-de-la-france-insoumise.html'},
    {id:'discord-node-12', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-12', name:"Mélenchon : le livre rouge du parfait petit populiste", author:"Contrepoints", link:'https://www.contrepoints.org/2017/04/12/286626-melenchon-livre-rouge-parfait-petit-populiste'},
    {id:'discord-node-13', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-13', name:"Dans les salons de discussions des soutiens de Mélenchon", author:"Slate", link:'http://www.slate.fr/story/135680/les-insoumis-discord-projets'},
    {id:'discord-node-14', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-14', name:"L’armée en ligne de Jean-Luc Mélenchon à l’heure de la désillusion", author:"Le Monde - Pixels", link:'https://www.lemonde.fr/pixels/article/2017/04/24/l-armee-en-ligne-de-jean-luc-melenchon-a-l-heure-de-la-desillusion_5116780_4408996.html'},
    {id:'discord-node-15', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-15', name:"Quand les “gilets jaunes” inspirent des jeux vidéo", author:"Les Inrockuptibles", link:'https://www.lesinrocks.com/2019/01/26/jeux-video/jeux-video/quand-les-gilets-jaunes-inspirent-des-jeux-video/'},
    {id:'discord-node-16', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-16', name:"Jean-Luc Mélenchon : \"Discord Les Insoumis\", le collectif militant issu de jeuxvideo.com", author:"RTL", link:'https://www.rtl.fr/actu/politique/jean-luc-melenchon-jeuxvideo-com-discord-les-insoumis-le-collectif-militant-7787758186'},
    {id:'discord-node-17', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-17', name:"Comment Mélenchon s'est offert une campagne numérique gratuite", author:"Le Point", link:'https://www.lepoint.fr/presidentielle/comment-melenchon-s-est-offert-une-campagne-numerique-gratuite-12-04-2017-2119180_3121.php'},
    {id:'discord-node-18', parent:"discord", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'discord-18', name:"Petite visite chez les activistes numériques de la «France insoumise»", author:"Libération", link:'https://www.liberation.fr/politiques/2017/02/20/petite-visite-chez-les-activistes-numeriques-de-la-france-insoumise_1549779'},
    /* DISCORD */
    {id:'reddit-node-1', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-1', name:"Exclusive: Reddit CEO talks about fending off Russian election interference", author:"NBC News", link:'https://www.nbcnews.com/tech/tech-news/exclusive-reddit-ceo-talks-about-fending-russian-election-interference-n921151'},
    {id:'reddit-node-2', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-2', name:"Reddit and the Struggle to Detoxify the Internet", author:"The New Yorker", link:'https://www.newyorker.com/magazine/2018/03/19/reddit-and-the-struggle-to-detoxify-the-internet'},
    {id:'reddit-node-3', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-3', name:"4chan and Reddit bombarded debate polls to declare Trump the winner", author:"The Daily Dot", link:'https://www.dailydot.com/layer8/trump-clinton-debate-online-polls-4chan-the-donald/'},
    {id:'reddit-node-4', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-4', name:"REDDIT CREATES 'WAR ROOM' TO FIGHT RUSSIAN ELECTION MEDDLING AND MISINFORMATION CAMPAIGNS", author:"Newsweek", link:'https://www.newsweek.com/reddit-creates-war-room-fight-russian-election-tampering-and-misinformation-1175916'},
    {id:'reddit-node-5', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-5', name:"Inside the white supremacist alt-right's terrifying election celebration", author:"Mic", link:'https://www.mic.com/articles/159070/alt-right-donald-trump-victory-celebration-racist-pepe-memes-anti-semitism-white-surpremacy-4chan-8chan-reddit'},
    {id:'reddit-node-6', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-6', name:"Reddit admits hosting Russian propaganda", author:"BBC News", link:"https://www.bbc.com/news/technology-43301643"},
    {id:'reddit-node-7', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-7', name:"Reddit infiltrated by Russian propaganda in run-up to US election", author:"The Guardian", link:"https://www.theguardian.com/technology/2018/mar/06/reddit-russian-propaganda-us-election"},
    {id:'reddit-node-8', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-8', name:"Trump Supporters Online Are Pretending To Be French To Manipulate France's Election", author:"BuzzFeed News", link:'https://www.buzzfeednews.com/article/ryanhatesthis/inside-the-private-chat-rooms-trump-supporters-are-using-to'},
    {id:'reddit-node-9', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-9', name:"Blaming the Media for Trump? Don’t Forget Facebook, Twitter and Reddit", author:"Variety", link:'https://variety.com/2016/digital/opinion/election-2016-blame-facebook-twitter-reddit-1201913946/'},
    {id:'reddit-node-10', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-10', name:"Pro-Donald Trump internet Reddit horde to turn attention to French elections", author:"The Sydney Morning Herald", link:'https://www.smh.com.au/world/north-america/prodonald-trump-internet-reddit-horde-to-turn-attention-to-french-elections-20161114-gsogn4.html'},
    {id:'reddit-node-11', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-11', name:"How an army of pro-Donald Trump trolls are taking over Reddit", author:"MSNBC", link:'http://www.msnbc.com/msnbc/how-donald-trumps-army-trolls-took-over-reddit'},
    {id:'reddit-node-12', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-12', name:"How Donald Trump won the 2016 meme wars", author:"The Conversation", link:'https://theconversation.com/how-donald-trump-won-the-2016-meme-wars-68580'},
    {id:'reddit-node-13', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-13', name:"Reddit admits it had a Russian troll problem during the election", author:"Vice", link:'https://news.vice.com/en_us/article/j5b3qy/reddit-admits-it-had-a-russian-troll-problem-during-the-election'},
    {id:'reddit-node-14', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-14', name:"White men radicalised online were amongst the 'silent majority' who chose Donald Trump", author:"The Independent", link:'https://www.independent.co.uk/news/world/americas/us-elections/donald-trump-white-men-online-radicalization-reddit-twitter-alt-right-latest-a7417296.html'},
    {id:'reddit-node-15', parent:"reddit", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'reddit-15', name:"Reddit was a misinformation hotspot in 2016 election, study says", author:"CNet", link:'https://www.cnet.com/news/reddit-election-misinformation-2016-research/'},
    /* JVC1825 */
    {id:'jvc1825-node-1', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-1', name:"VIDÉO - Marlène Schiappa sur jeuxvideo.com : \"Ce qui m'inquiète, ce sont les autres femmes qui sont harcelées sur le forum 18-25\"", author:"LCI", link:"https://www.lci.fr/societe/video-marlene-schiappa-sur-jeuxvideo-com-ce-qui-m-inquiete-ce-sont-les-autres-femmes-qui-sont-harcelees-sur-le-forum-18-25-2069489.html"},
    {id:'jvc1825-node-2', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-2', name:"Cyber-harcèlement : jeuxvideo.com, c'est quoi ce site dont les forums font polémique", author:"LCI", link:"https://www.lci.fr/societe/cyber-harcelement-trolls-jeuxvideo-com-blabla-18-25-nadia-daam-c-est-quoi-ce-site-dont-les-forums-font-polemique-2069311.html"},
    {id:'jvc1825-node-3', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-3', name:" Cyberharcèlement organisé chez jeuxvideo.com : Marlène Schiappa interpelle Twitter et Webedia", author:"Numérama", link:" https://www.numerama.com/politique/303164-cyberharcelement-organise-chez-jeuxvideo-com-marlene-schiappa-interpelle-twitter-et-webedia.html"},
    {id:'jvc1825-node-4', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-4', name:"Affaire Nadia Daam: jeuxvideo.com a-t-il fait des progrès ?", author:"L’Express", link:" https://lexpansion.lexpress.fr/high-tech/jeuxvideo-com-ou-en-est-la-moderation-du-meilleur-pire-forum-du-net-francais_2060915.html"},
    {id:'jvc1825-node-5', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-5', name:"Jean-Luc Mélenchon : \"Discord Les Insoumis\", le collectif militant issu de jeuxvideo.com", author:"RTL", link:"https://www.rtl.fr/actu/politique/jean-luc-melenchon-jeuxvideo-com-discord-les-insoumis-le-collectif-militant-7787758186"},
    {id:'jvc1825-node-6', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-6', name:"Un seul utilisateur générait plus de 6 % des liens redirigeant vers des sites de « réinformation »", author:"Le Monde - Les Décodeurs", link:"https://www.lemonde.fr/les-decodeurs/article/2017/04/02/les-forums-de-jeuxvideo-com-fers-de-lance-de-la-campagne-de-marine-le-pen_5104551_4355770.html"},
    {id:'jvc1825-node-7', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-7', name:"Antisémitisme, homophobie, fanatisme : Jeuxvideo.com, la ruche à fiel", author:"L’Obs", link:" https://www.nouvelobs.com/medias/20150924.OBS6430/antisemitisme-homophobie-fanatisme-jeuxvideo-com-la-ruche-a-fiel.html"},
    {id:'jvc1825-node-8', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-8', name:" Un faux foulard rouge se fait passer pour un organisateur de la manifestation à la télévision", author:"CNews", link:" https://www.cnews.fr/france/2019-01-29/un-faux-foulard-rouge-se-fait-passer-pour-un-organisateur-de-la-manifestation-la"},
    {id:'jvc1825-node-9', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-9', name:"Quand Florian Philippot utilise Risitas pour draguer la communauté de Jeuxvideo.com", author:"Les Inrockuptibles", link:"https://www.lesinrocks.com/2017/01/18/actualite/actualite/florian-philippot-utilise-risitas-draguer-communaute-de-jeuxvideo-com/"},
    {id:'jvc1825-node-10', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-10', name:"FLORIAN PHILIPPOT - PARLONS-EN #01 - TROMELIN", author:"Le Monde - Pixels", link:" https://www.lemonde.fr/pixels/article/2017/01/17/apres-jean-luc-melenchon-florian-phillippot-muliplie-les-clins-d-il-aux-forums-de-jeuxvideo-com_5064103_4408996.html"},
    {id:'jvc1825-node-11', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-11', name:"La troll de guerre des bataillons «antisystème»", author:"Libération", link:" https://www.liberation.fr/politiques/2017/03/20/la-troll-de-guerre-des-bataillons-antisysteme_1557137"},
    {id:'jvc1825-node-12', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-12', name:"A Issou, le harcèlement en ligne continue : tirons-en des leçons", author:"L’Obs", link:"https://www.nouvelobs.com/rue89/notre-epoque/20180222.OBS2590/a-issou-le-harcelement-en-ligne-continue-tirons-en-des-lecons.html"},
    {id:'jvc1825-node-13', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-13', name:"Le site Jeuxvideo.com va se plier au \"code de conduite\" de l'UE contre les discours haineux sur internet", author:"France TV Info", link:" https://www.francetvinfo.fr/internet/reseaux-sociaux/twitter/le-site-jeuxvideo-com-va-se-plier-au-code-de-conduite-de-l-ue-contre-les-discours-haineux-sur-internet_3174837.html"},
    {id:'jvc1825-node-14', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-14', name:"Deux membres du forum \"18-25\" de jeuxvideo.com condamnés à 6 mois de prison avec sursis pour avoir harcelé la journaliste Nadia Daam", author:"France TV Info", link:"https://www.francetvinfo.fr/societe/harcelement-sexuel/direct-harcelement-en-ligne-suivez-le-proces-des-internautes-qui-s-en-sont-pris-a-la-journaliste-nadia-daam_2831915.html"},
    {id:'jvc1825-node-15', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'jvc1825-15', name:"La nuit irréelle d'un député LREM sur Twitter", author:"L’Express", link:"https://www.lexpress.fr/actualite/politique/la-nuit-surrealiste-d-un-depute-lrem-sur-twitter_2055042.html"},
    // {id:'jvc1825-node-12', parent:"jvc1825", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'', name:"", author:"", link:''},
    /* THE_DONALD */
    {id:'r-the-donald-node-1', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-1', name:"\"The Great Meme War\" : comment les trolls de 4chan ont porté Trump au pouvoir", author:"Les Inrockuptibles", link:'https://www.lesinrocks.com/2017/03/28/medias/medias/the-great-meme-war-comment-les-trolls-de-4chan-ont-port%C3%A9-trump-au-pouvoir/'},
    {id:'r-the-donald-node-2', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-2', name:"Reddit, 4Chan : la victoire de Trump, c’est la victoire des trolls", author:"L'Obs", link:'https://www.nouvelobs.com/rue89/rue89-sur-les-reseaux/20161109.RUE4199/reddit-4chan-la-victoire-de-trump-c-est-la-victoire-des-trolls.html'},
    {id:'r-the-donald-node-3', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-3', name:"Reddit launches crackdown on 'most toxic' Donald Trump-supporting trolls", author:"The Independent", link:'https://www.independent.co.uk/news/world/americas/reddit-the-donald-trump-president-crackdown-online-abuse-trolls-a7449006.html'},
    {id:'r-the-donald-node-4', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-4', name:"Quand l'extrême droite américaine est prête à troller pour Marine Le Pen", author:"Slate", link:'http://www.slate.fr/story/128777/trump-centipedes-europe-france-le-pen'},
    {id:'r-the-donald-node-5', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-5', name:"WELCOME TO THE BIZARRO WORLD OF TRUMP SUPPORTERS ON REDDIT", author:"WIRED", link:'https://www.wired.com/2016/07/welcome-bizarro-world-trump-supporters-reddit/'},
    {id:'r-the-donald-node-6', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-6', name:"Reddit moves against 'toxic' Trump fans", author:"BBC News", link:'https://www.bbc.com/news/technology-38165435'},
    {id:'r-the-donald-node-7', parent:"r-the-donald", size:'medium', type:'media', subType:'site', folder:'sites', imgPopUp:'r-the-donald-7', name:"/r/The_Donald", author:"Know Your Meme", link:'https://knowyourmeme.com/memes/sites/rthe_donald'},
    {id:'r-the-donald-node-8', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-8', name:"Unpacking The_Donald, the internet’s pro-Trump bunker", author:"The Daily Dot", link:'https://www.dailydot.com/layer8/reddit-the-donald/'},
    {id:'r-the-donald-node-9', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-9', name:"Reddit just banned one of its most toxic forums. But it won’t touch The_Donald.", author:"Vox", link:'https://www.vox.com/culture/2017/11/13/16624688/reddit-bans-incels-the-donald-controversy'},
    {id:'r-the-donald-node-10', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-10', name:"La guerre entre le CEO de Reddit et le forum The_Donald est loin d’être terminée", author:"France 24", link:'https://www.france24.com/fr/20161129-guerre-entre-le-ceo-reddit-le-forum-thedonald-est-loin-etre-terminee'},
    {id:'r-the-donald-node-11', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-11', name:"How r/the_donald Became a Melting Pot of Frustration and Hate", author:"Vice", link:'https://www.vice.com/en_us/article/53d5xb/what-is-rthedonald-donald-trump-subreddit'},
    {id:'r-the-donald-node-12', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-12', name:"Reddit’s Theorists Give Up Trying to Explain Donald Trump’s Reddit Takeover", author:"Vice", link:'https://www.vice.com/en_us/article/53ddmz/analysts-decide-donald-trumps-reddit-reign-isnt-worth-trying-to-comprehend'},
    {id:'r-the-donald-node-13', parent:"r-the-donald", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'r-the-donald-13', name:"How Much Attention Should Extremists Get?", author:"The Atlantic", link:'https://www.theatlantic.com/politics/archive/2017/11/how-much-attention-should-extremists-get/546152/'},
    {id:'r-the-donald-node-14', parent:"r-the-donald", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'r-the-donald-14', name:"/r/The_Donald", author:"Wikipedia", link:'https://en.wikipedia.org/wiki//r/The_Donald'},
    /* SANDERS */
    {id:'sanders-stash-node-1', parent:"sanders-stash", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'sanders-stash-1', name:"Bernie Sanders' Dank Meme Stash", author:"Wikipedia", link:'https://en.wikipedia.org/wiki/Bernie_Sanders%27_Dank_Meme_Stash'},
    {id:'sanders-stash-node-2', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-2', name:"The Bernie Sanders Dank Meme Stash Is Dank Again After 2020 Announcement", author:"Inverse", link:'https://www.inverse.com/article/53395-bernie-sanders-dank-meme-stash-run-2020'},
    {id:'sanders-stash-node-3', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-3', name:"How Bernie Sanders became the lord of ‘dank memes’", author:"The Washington Post", link:'https://www.washingtonpost.com/news/the-intersect/wp/2016/02/23/how-bernie-sanders-became-the-lord-of-dank-memes/'},
    {id:'sanders-stash-node-4', parent:"sanders-stash", size:'medium', type:'media', subType:'site', folder:'sites', imgPopUp:'sanders-stash-4', name:"Bernie Sanders' Dank Meme Stash", author:"Know Your Meme", link:'https://knowyourmeme.com/memes/sites/bernie-sanders-dank-meme-stash'},
    {id:'sanders-stash-node-5', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-5', name:"Can Bernie Sanders’ Dank Meme Stash Swing the Election?", author:"Motherboard - Vice", link:'https://www.vice.com/en_us/article/d7ypwa/bernie-sanders-dank-meme-stash-facebook-page'},
    {id:'sanders-stash-node-6', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-6', name:"Angered Bernie Sanders online supporters say they will 'never vote for Hillary Clinton' and threaten to spoil their ballots or vote Trump", author:"The Telegraph", link:'https://www.telegraph.co.uk/news/2016/06/08/angered-bernie-sanders-online-say-they-will-never-vote-for-hilla/'},
    {id:'sanders-stash-node-7', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-7', name:"Bernie Sanders' Supporters Are Reacting to His Clinton Endorsement With These Memes", author:"attn", link:'https://archive.attn.com/stories/9863/sanders-supporters-react-clinton-endorsement-with-memes'},
    {id:'sanders-stash-node-8', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-8', name:"The Bernie Bros rule the Internet", author:"Yahoo! News", link:'https://www.yahoo.com/news/the-bernie-bros-rule-the-internet-180426111.html'},
    {id:'sanders-stash-node-9', parent:"sanders-stash", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'sanders-stash-9', name:"Bernie vs. Hillary", author:"Slate", link:'https://slate.com/technology/2016/02/the-bernie-vs-hillary-meme-is-weird-ceaseless-and-kind-of-sexist-just-like-the-2016-campaign.html'},
    /* TWITTER */
    {id:'twitter-node-1', parent:"twitter", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'twitter-1', name:"Twitter", author:"Wikipedia", link:'https://fr.wikipedia.org/wiki/Twitter'},
    {id:'twitter-node-2', parent:"twitter", size:'medium', type:'media', subType:'wiki', folder:'sites', imgPopUp:'twitter-2', name:"Donald Trump on social media", author:"Wikipedia", link:'https://en.wikipedia.org/wiki/Donald_Trump_on_social_media'},
    {id:'twitter-node-3', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-3', name:"The Fake Americans Russia Created to Influence the Election", author:"The New York Times", link:'https://www.nytimes.com/2017/09/07/us/politics/russia-facebook-twitter-election.html'},
    {id:'twitter-node-4', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-4', name:"Twitter CEO Jack Dorsey on Alex Jones, election security and regrets", author:"NBC News", link:'https://www.nbcnews.com/tech/tech-news/twitter-ceo-jack-dorsey-alex-jones-election-security-regrets-n900931'},
    {id:'twitter-node-5', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-5', name:"La « stratégie » Twitter du président élu Trump", author:"Le Monde", link:'https://www.lemonde.fr/ameriques/article/2017/01/07/la-strategie-twitter-du-president-elu-trump_5059103_3222.html'},
    {id:'twitter-node-6', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-6', name:"Donald Trump et Twitter, une utilisation compulsive et émotionnelle", author:"Les Décodeurs - Le Monde", link:'https://www.lemonde.fr/les-decodeurs/article/2017/01/24/compulsive-et-emotionnelle-quelle-est-l-utilisation-de-twitter-par-donald-trump_5068293_4355770.html'},
    {id:'twitter-node-7', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-7', name:"Trump a-t-il été élu grâce à Twitter ? Si c’est le cas, le réseau social en est « désolé »", author:"Numérama", link:'https://www.numerama.com/politique/260067-trump-a-t-il-ete-elu-grace-a-twitter-si-cest-le-cas-le-reseau-social-en-est-desole.html'},
    {id:'twitter-node-8', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-8', name:"Election de Trump : sur Twitter, des contenus promotionnels financés depuis la Russie", author:"Le Parisien", link:'http://www.leparisien.fr/international/election-de-trump-sur-twitter-des-contenus-promotionnels-finances-depuis-la-russie-29-09-2017-7294614.php'},
    {id:'twitter-node-9', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-9', name:"Deepfakes are coming. Facebook, Twitter and YouTube might not be ready", author:"CNet", link:'https://www.cnet.com/news/facebook-twitter-and-youtube-grapple-with-altered-videos-ahead-of-the-2020-election/'},
    {id:'twitter-node-10', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-10', name:"«Twitter est devenu aussi indissociable de Donald Trump que sa chevelure et sa cravate», juste un an après son élection", author:"20 Minutes", link:'https://www.20minutes.fr/high-tech/2164763-20171107-twitter-devenu-aussi-indissociable-donald-trump-chevelure-cravate-juste-an-apres-election'},
    {id:'twitter-node-11', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-11', name:"Election de Trump : le double discours de Twitter", author:"La Tribune", link:'https://www.latribune.fr/technos-medias/election-de-trump-le-double-discours-de-twitter-719745.html'},
    {id:'twitter-node-12', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-12', name:"Peut-on vraiment faire confiance à Twitter pour prédire les résultats d'une élection?", author:"Slate", link:'http://www.slate.fr/story/93483/twitter-predire-resultats-election'},
    {id:'twitter-node-13', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-13', name:"Twitter reconnaît mais nuance les tentatives russes d’influencer l’élection de 2016", author:"Pixels - Le Monde", link:'https://www.lemonde.fr/pixels/article/2018/01/29/twitter-reconnait-mais-nuance-les-tentatives-russes-d-influencer-l-election-de-2016_5248830_4408996.html'},
    {id:'twitter-node-14', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-14', name:"Russia's manipulation of Twitter was far vaster than believed", author:"Politico", link:'https://www.politico.com/story/2019/06/05/study-russia-cybersecurity-twitter-1353543'},
    {id:'twitter-node-15', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-15', name:"Election américaine : 1,4 million d’utilisateurs de Twitter confrontés à la propagande russe", author:"Pixels - Le Monde", link:'https://www.lemonde.fr/pixels/article/2018/02/01/election-americaine-1-4-million-d-utilisateurs-de-twitter-confrontes-a-la-propagande-russe_5250315_4408996.html'},
    {id:'twitter-node-16', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-16', name:"Why has Twitter banned 1500 accounts and what are NPCs?", author:"BBC News", link:'https://www.bbc.com/news/blogs-trending-45888176'},
    {id:'twitter-node-17', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-17', name:"4Chan Sparks Mass Triggering With NPC Meme; Twitter Responds With Ban Hammer", author:"Zero Hedge", link:'https://www.zerohedge.com/news/2018-10-16/4chan-sparks-mass-triggering-npc-meme-twitter-responds-ban-hammer'},
    {id:'twitter-node-18', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-18', name:"What are NPCs and why has Twitter banned them?", author:"The Week", link:'https://www.theweek.co.uk/97291/what-are-npcs-and-why-has-twitter-banned-them'},
    {id:'twitter-node-19', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-19', name:"Twitter suspends accounts for ‘coordinated’ far-right trolling campaign", author:"The New York Post", link:'https://nypost.com/2018/10/18/twitter-suspends-accounts-for-coordinated-far-right-trolling-campaign/'},
    {id:'twitter-node-20', parent:"twitter", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'twitter-20', name:"Quand mèmes et émojis anodins deviennent des outils de communication pour les groupes extrémistes", author:"20 Minutes", link:'https://www.20minutes.fr/high-tech/2361519-20181026-quand-memes-emojis-anodins-deviennent-outils-communication-groupes-extremistes'},

    // {id:'-node-', parent:"", size:'medium', type:'media', subType:'news', folder:'sites', imgPopUp:'', name:"", author:"", link:''},

  ],
  links: [
    /* 4CHAN to NODES */
    {source:'4chan', target:'4chan-node-1', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-2', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-3', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-4', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-5', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-6', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-7', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-8', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-9', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-10', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-11', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-12', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-13', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-14', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-15', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-16', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-17', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-18', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-19', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-20', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-21', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-22', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-23', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-24', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-25', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-26', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-27', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-28', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-29', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-30', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-31', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-32', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-33', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-34', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-35', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-36', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-37', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-38', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-39', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-40', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-41', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-42', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-43', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-44', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-45', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-46', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-47', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-48', type:'neutral', weight:1},
    {source:'4chan', target:'4chan-node-49', type:'neutral', weight:1},
    /* REDDIT to NODES */
    {source:'reddit', target:'reddit-node-1', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-2', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-3', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-4', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-5', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-6', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-7', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-8', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-9', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-10', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-11', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-12', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-13', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-14', type:'neutral', weight:1},
    {source:'reddit', target:'reddit-node-15', type:'neutral', weight:1},
    /* DISCORD to NODES */
    {source:'discord', target:'discord-node-1', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-2', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-3', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-4', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-5', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-6', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-7', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-8', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-9', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-10', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-11', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-12', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-13', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-14', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-15', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-16', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-17', type:'neutral', weight:1},
    {source:'discord', target:'discord-node-18', type:'neutral', weight:1},
    /* jvc1825 to NODES */
    {source:'jvc1825', target:'jvc1825-node-1', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-2', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-3', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-4', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-5', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-6', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-7', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-8', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-9', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-10', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-11', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-12', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-13', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-14', type:'neutral', weight:1},
    {source:'jvc1825', target:'jvc1825-node-15', type:'neutral', weight:1},
    /*  THE DONALD to NODES */
    {source:'r-the-donald', target:'r-the-donald-node-1', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-2', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-3', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-4', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-5', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-6', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-7', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-8', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-9', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-10', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-11', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-12', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-13', type:'neutral', weight:1},
    {source:'r-the-donald', target:'r-the-donald-node-14', type:'neutral', weight:1},
    /* SANDERS STASH to NODES */
    {source:'sanders-stash', target:'sanders-stash-node-1', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-2', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-3', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-4', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-5', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-6', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-7', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-8', type:'neutral', weight:1},
    {source:'sanders-stash', target:'sanders-stash-node-9', type:'neutral', weight:1},
    /* TWITTER to NODES */
    {source:'twitter', target:'twitter-node-1', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-2', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-3', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-4', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-5', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-6', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-7', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-8', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-9', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-10', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-11', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-12', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-13', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-14', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-15', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-16', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-17', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-18', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-19', type:'neutral', weight:1},
    {source:'twitter', target:'twitter-node-20', type:'neutral', weight:1},
    /*  to NODES */
    /*  to NODES */
    /* SITES to SITES */
    // {source:'4chan', target:'twitter', type:'neutral', weight:0},
    {source:'4chan', target:'discord', type:'neutral', weight:0},
    {source:'4chan', target:'reddit', type:'neutral', weight:0},
    {source:'4chan', target:'jvc1825', type:'neutral', weight:0},
    {source:'reddit', target:'r-the-donald', type:'neutral', weight:3},
    {source:'4chan', target:'sanders-stash', type:'neutral', weight:0},
    {source:'4chan', target:'twitter', type:'neutral', weight:0},
  ]
}
